<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>SnowRunner_Tool</RootNamespace>
    <AssemblyName>SnowRunner-Tool</AssemblyName>
    <ApplicationIcon>baseline_restore_black_18dp.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.5.3</Version>
    <AssemblyVersion>1.0.5.3</AssemblyVersion>
    <FileVersion>1.0.5.3</FileVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <NoWarn>$(NoWarn);CA1416;SYSLIB0003;NU1701</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>P:\snowrunner\Debug\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="ControlzEx" Version="5.0.2" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="4.11.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.141" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Octokit" Version="10.0.0" />
    <PackageReference Include="RestoreWindowPlace" Version="2.1.0" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Changelog.md" Link="Changelog.md" CopyToOutputDirectory="Always" />
    <None Include="..\copying" Link="copying" CopyToOutputDirectory="Always" />
    <None Include="..\Readme.md" Link="Readme.md" CopyToOutputDirectory="Always" />
    <None Include="placement.config" CopyToOutputDirectory="Always" />
    <None Include="..\innosetup\setup.iss" Link="setup.iss" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\baseline_done_black_18dp.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="images\baseline_done_black_18dp_1x.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
